const navigation = '<!DOCTYPE html>'
  + '<html>'
  + '<head>'
  + '<link rel="stylesheet" href="/center.css" />'
  + '</head>'
  + '<body>'
  + '<div class="center">'
  + '<a href="/">Home</a> &nbsp;&nbsp;'
  + '<a href="/product-form">Product Form</a> &nbsp;&nbsp;'
  + '<a href="/product-table">Product Table</a> &nbsp;&nbsp;'
  + '<a href="/user-form">User Form</a> &nbsp;&nbsp;'
  + '<a href="/user-table">User Table</a> &nbsp;&nbsp;'
  + '<a href="/">Exit</a>'
  + '</div>'
  + '<h2 class="center">Dashboard</h2>'
  + '</body>'
  + '</html>'

module.exports = navigation;