const productTable = '<!DOCTYPE html>'
  + '<html>'
  + '<head>'
  + '<link rel="stylesheet" href="/center.css" />'
  + '<link rel="stylesheet" href="/table.css" />'
  + '</head>'
  + '<body>'
  + '<h2 class="center">Product Table</h2>'
  + '<table id="table" class="table-center">'
  + '<tr>'
  + '<th>Index</th>'
  + '<th>Name</th>'
  + '<th>Quantity</th>'
  + '<th>Price</th>'
  + '<th>Edit</th>'
  + '<th>Delete</th>'
  + '</tr>'
  + '{ROWS}'
  + '</table>'
  + '</body>'
  + '</html>'

module.exports = productTable;
