const productForm = '<!DOCTYPE html>'
  + '<html>'
  + '<head>'
  + '<link rel="stylesheet" href="/center.css" />'
  + '<link rel="stylesheet" href="/form.css" />'
  + '<script src="/utils-local-storage.js"></script>'
  + '<script src="/mock-data.js"></script>'
  + '<script src="/product-form.js"></script>'
  + '</head>'
  + '<body onload="onLoadFormEdit()">'
  + '<h2 class="center">Product Form</h2>'
  + '<form onsubmit="event.preventDefault();onFormSubmit();" class="center">'
  + '<fieldset>'
  + '<label for="name">Name:</label>'
  + '<input type="text" id="name" />'
  + '<br /><br />'
  + '<label for="quantity">Quantity:</label>'
  + '<input type="text" id="quantity" />'
  + '<br /><br />'
  + '<label for="price">Price:</label>'
  + '<input type="text" id="price" />'
  + '<br /><br />'
  + '<input type="submit" value="Submit" />'
  + '</fieldset>'
  + '</form>'
  + '</body>'
  + '</html>'

module.exports = productForm;
