const userTable = '<!DOCTYPE html>'
  + '<html>'
  + '<head>'
  + '<link rel="stylesheet" href="/center.css" />'
  + '<link rel="stylesheet" href="/table.css" />'
  + '<script src="/mock-data.js"></script>'
  + '<script src="/utils-local-storage.js"></script>'
  + '<script src="/user-table.js"></script>'
  + '</head>'
  + '<body onload="updateTableUser()">'
  + '<h2 class="center">User Table</h2>'
  + '<table id="table" class="table-center">'
  + '<tr>'
  + '<th>Index</th>'
  + '<th>Nickname</th>'
  + '<th>Password</th>'
  + '<th>Names</th>'
  + '<th>LastName</th>'
  + '<th>Birthday</th>'
  + '<th>Email</th>'
  + '<th>Type</th>'
  + '<th>Edit</th>'
  + '<th>Delete</th>'
  + '</tr>'
  + '</table>'
  + '</body>'
  + '</html>'

module.exports = userTable;
